# HTTP Server
server:
  context-path: /users
  port: 1111   # HTTP (Tomcat) port
  
# Discovery Server Access
eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 10  
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#      healthcheck:
#        enabled: true   
    region: default
    registryFetchIntervalSeconds: 5
    availabilityZones: 
      default: ${APPLICATION_DOMAIN:${DOMAIN:defaultZone}} 


# Endpoint setup
endpoints:
  restart:
    enabled: true

# Logging
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG